"""migration

Revision ID: 6fa896fccb73
Revises: 
Create Date: 2021-12-25 11:32:39.549237

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fa896fccb73'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('category_name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('category_id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('firstname', sa.String(length=100), nullable=True),
    sa.Column('lastname', sa.String(length=100), nullable=True),
    sa.Column('companyname', sa.String(length=100), nullable=True),
    sa.Column('companyinitials', sa.String(length=100), nullable=True),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.Column('phone_no', sa.String(length=100), nullable=True),
    sa.Column('role', sa.String(length=100), nullable=True),
    sa.Column('primary_contact', sa.String(length=100), nullable=True),
    sa.Column('postal_code', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('messages',
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=1000), nullable=True),
    sa.Column('media', sa.String(length=200), nullable=True),
    sa.Column('reciever', sa.Integer(), nullable=True),
    sa.Column('sended_by', sa.Integer(), nullable=True),
    sa.Column('posted_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['reciever'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sended_by'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('message_id')
    )
    op.create_table('notifications',
    sa.Column('notification_id', sa.Integer(), nullable=False),
    sa.Column('notification_created_by', sa.Integer(), nullable=True),
    sa.Column('notification_for', sa.Integer(), nullable=True),
    sa.Column('text', sa.String(length=100), nullable=True),
    sa.Column('is_seen', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['notification_created_by'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['notification_for'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('notification_id')
    )
    op.create_table('products',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('posted_by', sa.Integer(), nullable=True),
    sa.Column('posted_date', sa.Date(), nullable=True),
    sa.Column('product_name', sa.String(length=200), nullable=True),
    sa.Column('product_description', sa.String(length=1000), nullable=True),
    sa.Column('quality_description', sa.String(length=1000), nullable=True),
    sa.Column('sku_code', sa.String(length=100), nullable=True),
    sa.Column('moq', sa.String(length=100), nullable=True),
    sa.Column('product_picture1', sa.String(length=200), nullable=True),
    sa.Column('product_picture2', sa.String(length=200), nullable=True),
    sa.Column('product_picture3', sa.String(length=200), nullable=True),
    sa.Column('price', sa.String(length=100), nullable=True),
    sa.Column('tags', sa.String(length=200), nullable=True),
    sa.Column('stock_keeping_unit', sa.String(length=100), nullable=True),
    sa.Column('variant', sa.String(length=100), nullable=True),
    sa.Column('tax_tier', sa.String(length=100), nullable=True),
    sa.Column('order_unit', sa.String(length=100), nullable=True),
    sa.Column('hsn_code', sa.String(length=100), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['posted_by'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('product_id')
    )
    op.create_table('recent_chats',
    sa.Column('recent_chat_id', sa.Integer(), nullable=False),
    sa.Column('recent_chat', sa.Integer(), nullable=True),
    sa.Column('recent_chat_for', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['recent_chat'], ['users.id'], ),
    sa.ForeignKeyConstraint(['recent_chat_for'], ['users.id'], ),
    sa.PrimaryKeyConstraint('recent_chat_id')
    )
    op.create_table('cart',
    sa.Column('cart_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('cart_id')
    )
    op.create_table('favorite_products',
    sa.Column('favorite_id', sa.Integer(), nullable=False),
    sa.Column('favorite_product_id', sa.Integer(), nullable=True),
    sa.Column('favorite_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['favorite_by'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['favorite_product_id'], ['products.product_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('favorite_id')
    )
    op.create_table('placed_orders',
    sa.Column('placed_order_id', sa.Integer(), nullable=False),
    sa.Column('posted_date', sa.Date(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('order_product_id', sa.Integer(), nullable=True),
    sa.Column('placed_by', sa.Integer(), nullable=True),
    sa.Column('order_cart_id', sa.Integer(), nullable=True),
    sa.Column('is_accepted', sa.Integer(), nullable=True),
    sa.Column('is_completed', sa.Integer(), nullable=True),
    sa.Column('is_rejected', sa.Integer(), nullable=True),
    sa.Column('placed_order_address', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['order_cart_id'], ['cart.cart_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['order_product_id'], ['products.product_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['placed_by'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('placed_order_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('placed_orders')
    op.drop_table('favorite_products')
    op.drop_table('cart')
    op.drop_table('recent_chats')
    op.drop_table('products')
    op.drop_table('notifications')
    op.drop_table('messages')
    op.drop_table('users')
    op.drop_table('categories')
    # ### end Alembic commands ###
